
--------------------------------------------------------------
-- Database creation Script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- Verbose generation: ON

-- note: spaces within table/column names have been replaced by underscores (_)

-- Target DB: SQL2

-- Entity Model :Crime Type Frequency

-- To drop the tables generated by this script run -
--   'C:\Users\NEW IT WIZARD\OneDrive\Desktop\Database\Assessment Part1\SS_DDL_drop.sql'

--------------------------------------------------------------
-- Dropping a table has the effect of removing it from the Database.  All existing data is lost
-- as well as the definition of the table itself (stored as meta-data).  Dropping the tables allows
-- them to be re-created within the Database, even if they already exist.


--------------------------------------------------------------

-- Drop tables --

DROP TABLE DIM_TIME CASCADE CONSTRAINTS;

DROP TABLE DIM_LOCATION CASCADE CONSTRAINTS;

DROP TABLE DIM_STATUS CASCADE CONSTRAINTS;

DROP TABLE DIM_CRIME_TYPE CASCADE CONSTRAINTS;

DROP TABLE FACT_CRIME_TYPE_FREQUENCY CASCADE CONSTRAINTS;



--------------------------------------------------------------
-- Table Creation --

-- Each entity on the model is represented by a table that needs to be created within the Database.
-- Within SQL new tables are created using the CREATE TABLE command.
-- When a table is created its name and its attributes are defined.
-- The values of which are derived from those specified on the model.
-- Certain constraints are sometimes also specified, such as identification of primary keys.

-- Create a Database table to represent the "DIM_TIME" entity.
CREATE TABLE DIM_TIME(
	time_id	INTEGER NOT NULL,
	full_date	DATE,
	day	INTEGER,
	month	VARCHAR(20),
	year	INTEGER,
	-- Specify the PRIMARY KEY constraint for table "DIM_TIME".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_DIM_TIME PRIMARY KEY (time_id)
);

-- Create a Database table to represent the "DIM_LOCATION" entity.
CREATE TABLE DIM_LOCATION(
	location_id	INTEGER NOT NULL,
	area_id_original	INTEGER,
	area	VARCHAR(100),
	region_id_original	INTEGER,
	region	VARCHAR(100),
	station_id_original	INTEGER,
	station	VARCHAR(100),
	-- Specify the PRIMARY KEY constraint for table "DIM_LOCATION".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_DIM_LOCATION PRIMARY KEY (location_id)
);

-- Create a Database table to represent the "DIM_STATUS" entity.
CREATE TABLE DIM_STATUS(
	status_id	INTEGER NOT NULL,
	status_description	VARCHAR(200),
	-- Specify the PRIMARY KEY constraint for table "DIM_STATUS".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_DIM_STATUS PRIMARY KEY (status_id)
);

-- Create a Database table to represent the "DIM_CRIME_TYPE" entity.
CREATE TABLE DIM_CRIME_TYPE(
	crime_type_id	INTEGER NOT NULL,
	crime_type_id_original	INTEGER,
	crime_type_description	VARCHAR(200),
	-- Specify the PRIMARY KEY constraint for table "DIM_CRIME_TYPE".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_DIM_CRIME_TYPE PRIMARY KEY (crime_type_id)
);

-- Create a Database table to represent the "FACT_CRIME_TYPE_FREQUENCY" entity.
CREATE TABLE FACT_CRIME_TYPE_FREQUENCY(
	fact_crime_type_id	INTEGER NOT NULL,
	crime_count	INTEGER,
	reported_crime_id_original	INTEGER,
	is_closed_flag	INTEGER,
	is_escalated_flag	INTEGER,
	fk_time_id	INTEGER,
	fk_location_id	INTEGER,
	fk_status_id	INTEGER,
	fk_crime_type_id	INTEGER,
	-- Specify the PRIMARY KEY constraint for table "FACT_CRIME_TYPE_FREQUENCY".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_FACT_CRIME_TYPE_FREQUENCY PRIMARY KEY (fact_crime_type_id)
);


--------------------------------------------------------------
-- Alter Tables to add fk constraints --

-- Now all the tables have been created the ALTER TABLE command is used to define some additional
-- constraints.  These typically constrain values of foreign keys to be associated in some way
-- with the primary keys of related tables.  Foreign key constraints can actually be specified
-- when each table is created, but doing so can lead to dependency problems within the script
-- i.e. tables may be referenced before they have been created.  This method is therefore safer.

-- Alter table to add new constraints required to implement the "FACT_CRIME_TYPE_FREQUENCY_DIM_TIME" relationship

-- This constraint ensures that the foreign key of table "FACT_CRIME_TYPE_FREQUENCY"
-- correctly references the primary key of table "DIM_TIME"

ALTER TABLE FACT_CRIME_TYPE_FREQUENCY ADD CONSTRAINT fk1_FACT_CRIME_TYPE_FREQUENCY_to_DIM_TIME FOREIGN KEY(fk_time_id) REFERENCES DIM_TIME(time_id);

-- Alter table to add new constraints required to implement the "FACT_CRIME_TYPE_FREQUENCY_DIM_LOCATION" relationship

-- This constraint ensures that the foreign key of table "FACT_CRIME_TYPE_FREQUENCY"
-- correctly references the primary key of table "DIM_LOCATION"

ALTER TABLE FACT_CRIME_TYPE_FREQUENCY ADD CONSTRAINT fk2_FACT_CRIME_TYPE_FREQUENCY_to_DIM_LOCATION FOREIGN KEY(fk_location_id) REFERENCES DIM_LOCATION(location_id);

-- Alter table to add new constraints required to implement the "FACT_CRIME_TYPE_FREQUENCY_DIM_STATUS" relationship

-- This constraint ensures that the foreign key of table "FACT_CRIME_TYPE_FREQUENCY"
-- correctly references the primary key of table "DIM_STATUS"

ALTER TABLE FACT_CRIME_TYPE_FREQUENCY ADD CONSTRAINT fk3_FACT_CRIME_TYPE_FREQUENCY_to_DIM_STATUS FOREIGN KEY(fk_status_id) REFERENCES DIM_STATUS(status_id);

-- Alter table to add new constraints required to implement the "FACT_CRIME_TYPE_FREQUENCY_DIM_CRIME_TYPE" relationship

-- This constraint ensures that the foreign key of table "FACT_CRIME_TYPE_FREQUENCY"
-- correctly references the primary key of table "DIM_CRIME_TYPE"

ALTER TABLE FACT_CRIME_TYPE_FREQUENCY ADD CONSTRAINT fk4_FACT_CRIME_TYPE_FREQUENCY_to_DIM_CRIME_TYPE FOREIGN KEY(fk_crime_type_id) REFERENCES DIM_CRIME_TYPE(crime_type_id);


--------------------------------------------------------------
-- End of DDL file auto-generation
--------------------------------------------------------------
